<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<ProduceReferenceAssembly>False</ProduceReferenceAssembly>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageId>Lebi.Titan.Cheese</PackageId>
		<Title>Titan.Cheese</Title>
		<Authors>Lebi</Authors>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/LebiFur/Titan.Cheese.git</RepositoryUrl>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
	</PropertyGroup>
	<ItemGroup>
		<None Update="LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Update="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
</Project>
